sudo: required

go_import_path: github.com/KyberNetwork/cache

language: go

go:
  - "1.13.6"

services:
  - docker

install:
  - echo “skip”

after_success:
  - docker --version
  - docker build -f Dockerfile -t kybernetwork/wallet-cache:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push
    on:
      all_branches: true

  - provider: script
    script: bash .travis/awx_job_launch $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
